### ISSUE TITLE
Embedding local asciinema files into web pages broken

### ISSUE THREAD

**Issue by Thorsten-Sick** [divi255/sphinxcontrib.asciinema#11]
Security settings in modern browsers prevent mixing the web based player with local cast files.

The workaround is to directly embed the data as base64 data url: https://github.com/asciinema/asciinema-player/issues/64

It would be great to automatically generate base64 encoded data from the ascii-cast and create the specific data url.

If this can not be done default, maybe offer a configuration switch to make this optional

**Comment by divi255** [comment]
thanks for the request. I'll think about it when have a time
