### ISSUE TITLE
Add font-family option for asciinema player

### ISSUE THREAD

**Issue by PierreMarchand20** [divi255/sphinxcontrib.asciinema#19]
Looking at the documentation of the asciinema player : https://github.com/asciinema/asciinema-player#terminalfontfamily it should be possible to change `font-family` the same way we can change `font-size`. But it does not seem to work via this sphinx extension, and looking quickly at the source code, the option `font-size` does appear [here](https://github.com/divi255/sphinxcontrib.asciinema/blob/master/sphinxcontrib/asciinema/asciinema.py#L66) but not `font-family`. Would it be possible to add this option?

**Comment by divi255** [comment]
Hi,

Will look on this soon

**Comment by divi255** [comment]
Sorry for the delay, have a lot of tasks last time. It seems it is enough to enable the font-family in option_spec. Try 0.3.4, should work

**Comment by PierreMarchand20** [comment]
Do I need to do something special to update it ? I just used `pip3 install sphinxcontrib.asciinema --upgrade`, but my sphinx project does not seem able to set the option.

It does not work when I try to set it and here's autocompletion only showing `font-size`:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/15056323/176540510-8faeff4c-7900-4a75-96e5-d10b02914f1b.png">

**Comment by divi255** [comment]
make sure you have 0.3.4
pip3 list|grep sphinxcontrib.asciinema

**Comment by PierreMarchand20** [comment]
Ok, so I think the issue is that the feature was added in `asciinema-player` recently (https://github.com/asciinema/asciinema-player/pull/175) with v3.0, and the version shipped with your extension is <3.0.

**Comment by PierreMarchand20** [comment]
I guess it should be fairly doable to update it, it was done [here](https://github.com/cljoly/gohugo-asciinema) for a go/hugo module for example.
