### ISSUE TITLE
Remove !important from asciinema-custom.css 

### ISSUE THREAD

**Issue by PierreMarchand20** [divi255/sphinxcontrib.asciinema#20]
User's configuration cannot override `text-align` from `.asciinema-player-wrapper` in [asciinema-custom.css](https://github.com/divi255/sphinxcontrib.asciinema/blob/master/sphinxcontrib/asciinema/_static/asciinema-custom.css#L11) because of `!important`. Would it be possible to remove it?

**Comment by divi255** [comment]
sorry for the delay. fixed in 0.3.5
