### ISSUE TITLE
Error in "asciinema" directive: unknown option: "title"

### ISSUE THREAD

**Issue by zerocewl** [divi255/sphinxcontrib.asciinema#25]
With the update of `sphinxcontrib.asciinema` to `v0.4.0` we get an issue

```sh
/builds/.../test.rst:80: ERROR: Error in "asciinema" directive:
unknown option: "title".
.. asciinema:: examples/test.cast
   :poster: npt:0:03
   :cols: 300
   :rows: 38
   :title: my test title
```

The change comes with `update of asciinema from 2.6.1 to 3.6.3` PULLREQUEST: https://github.com/divi255/sphinxcontrib.asciinema/pull/24

and the remove of the `title` [in this line](https://github.com/divi255/sphinxcontrib.asciinema/pull/24/files#diff-f58be37fc336c2922345af543a7c769e5f0ecacdfba99bc771777eac14cd1f0eL70)

`'title': directives.unchanged,`

Is this intended?

**Comment by divi255** [comment]
good day,

the asciinema player has been updated to 3.x. I'll take a look if they kept title parameter

**Comment by zerocewl** [comment]
hm looks like they removed it with `v3`?

https://github.com/asciinema/asciinema-player/releases/tag/v3.0.0

![image](https://github.com/divi255/sphinxcontrib.asciinema/assets/9155214/44af8c75-ecc8-4f40-b031-e4e9e3c81b5e)

**Comment by divi255** [comment]
seems so
