### ISSUE TITLE
All options are passed to asciinema-player as string

### ISSUE THREAD

**Issue by Sarkutz** [divi255/sphinxcontrib.asciinema#27]
Some asciinema-player options are non-string options.  For example, the [markers](https://docs.asciinema.org/manual/player/options/#markers) option is a list.

Currently, all options are passed to asciinema-player as string [here](https://github.com/divi255/sphinxcontrib.asciinema/blob/master/sphinxcontrib/asciinema/asciinema.py#L47).  Hence, asciinema-player does not honour those options.

Is it possible to pass options to asciinema-player as per their type?

I faced this issue with markers option in `sphinxcontrib.asciinema==0.4.1` using a local asciinema file.

Thank You for this great extension!

**Comment by divi255** [comment]
markers are now passed as raw, with no quotes in 0.4.2. unfortunately it seems to way to specify markers for non self-hosted videos as "data" script tag properties accept strings only
