### ISSUE TITLE
Possible to set source directory default path?

### ISSUE THREAD

**Issue by MatthewCroughan** [divi255/sphinxcontrib.asciinema#8]
The docs I am working on have a `source/_static/asciinema` folder in which all casts will be placed. Instead of having to refer to this full path like this:

```
.. asciinema:: ../_static/asciinema/set-device-tags.cast
```
It would be great if we could just refer to it like this:
```
.. asciinema:: set-device-tags.cast
```

Perhaps it could be a config option?
```
sphinxcontrib_asciinema_defaults = {
       'path': source/_static/asciinema
}
```

**Comment by divi255** [comment]
added in https://github.com/divi255/sphinxcontrib.asciinema/commit/a5451cc117956040e4d139a1eec8c3af3636d462
