### ISSUE TITLE
Crashes when building with singlehtml

### ISSUE THREAD

**Issue by MatthewCroughan** [divi255/sphinxcontrib.asciinema#9]
Using `sphinx-build -b singlehtml` crashes sphinxcontrib.asciinema with:

```
Exception occurred:
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/asciinema/asciinema.py", line 38, in visit_html
    for n, v in node.options.items():
AttributeError: 'Asciinema' object has no attribute 'options'
```

**Comment by divi255** [comment]
thanks for reporting. I hope to check both issues during the weekend

**Comment by MatthewCroughan** [comment]
Fantastic. I love this plugin. It makes documentation so much more fun and modern :smile:

**Comment by divi255** [comment]
I've found the code didn't work properly with Sphinx 3.x+, it's strange how HTML parser worked. I've made full directive options refactoring, seems to work now (v0.2.0 published)
